# Generated by Django 4.2.1 on 2023-05-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
