# Generated by Django 4.2.1 on 2023-06-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_category_created_at_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=255, verbose_name='url')),
                ('content', models.TextField(verbose_name='запись')),
                ('picture', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Картинка')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Статус публикации')),
                ('views', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
        ),
    ]
