# Generated by Django 4.2.1 on 2023-06-28 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_blog_picture_alter_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(blank=True, verbose_name='Номер версии')),
                ('version_name', models.CharField(max_length=255, verbose_name='Наименование версии')),
                ('version_attribute', models.BooleanField(default=True, verbose_name='Статус версии')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.product', verbose_name='Наименование продукта')),
            ],
        ),
    ]
